logos/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'logos'

urlpatterns = [
    #/
    url(r'^$', views.home_view ,name ="home_view"),

    #/search/text/
    url(r'^search/<text>[a-z]+/$', views.search_view ,name = "search_view"),
    
    #/logos/
    url(r'^logos/$', views.logos_view , name = "logos_view"),

    #/logos/pk/
    url(r'^logos/(?P<pk>[0-9]+)/$', views.logo_detail_view ,name = "logo_detail_view"),

    #/logos/download/pk/
    url(r'^logos/download/(?P<pk>[0-9]+)/$', views.logo_download_view ,name = "logo_download_view"),


]

myWebsite/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'', include('logos.urls')),
    url(r'', include('request.urls')),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

request/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'request'

urlpatterns = [
    #/requests/
    url(r'^requests/$',views.requests_view.as_view() ,name="requests_view"),
 
    #/requests/pk/
    url(r'^requests/(?P<pk>[0-9]+)/$', views.request_detail_view.as_view() ,name = "request_detail_view"),

    #/request/pk/create/
    #url(r'^requests/(?P<pk>[0-9]+)/create/$', views.create_view ,name = "create_view"),

]

logos/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Logo(models.Model):
    logo_img = models.FileField(default = "None")
    logo_name = models.CharField(max_length = 30)
    logo_type = models.CharField(max_length = 30)
    software_used = models.CharField(max_length = 100, blank = "True")
    requested_by = models.CharField(max_length = 30, blank = "True")
    created_by = models.CharField(max_length = 30)
    create_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.logo_name
    
                                       

request/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Request(models.Model):
    requested_by = models.CharField(max_length = 30)
    email = models.EmailField(max_length=254)
    discription = models.TextField()
    logo_type = models.CharField(max_length = 30)
    usage = models.CharField(max_length=30)
    is_created = models.BooleanField(default="False")
    request_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.requested_by

    def completed(self):
        self.is_created = "True"

logos/views.py
from django.shortcuts import render,get_object_or_404
from .models import Logo

# for downloading files
from django.http import FileResponse
from django.utils.text import slugify
import os

def home_view(request):
    return render(request , 'logos/home_page.html' ,{})
    
def logos_view(request):
    all_logos = Logo.objects.all()
    return render(request , 'logos/logos_page.html' , {'all_logos':all_logos})

def logo_detail_view(request,pk):
    logo = get_object_or_404(Logo,pk=pk)
    return render(request,'logos/logo_detail_page.html' ,{'logo':logo})

def search_view(request):
    query = request.GET.get('q')
    searched_logos = Logo.objects.filter(logo_name__contains = query)or Logo.objects.filter(logo_type__contains = query)
    context = {'searched_logos':searched_logos , 'query' : query}
    return render(request , 'logos/search_page.html' , context)


def logo_download_view(request, pk):
    item = get_object_or_404(Logo, pk=pk)
    file = item.logo_img
    file_name, file_extension = os.path.splitext(file.url)
    file_extension = file_extension[1:] # removes dot
    response = FileResponse(file, 
      content_type = "file/%s"  %(file_extension))
    response["Content-Disposition"] = "attachment;"\
        "filename=%s-%s.%s" %(item.logo_name,item.logo_type,file_extension)
    return response

request/views.py
from django.shortcuts import render
from django.views import generic
from .models import Request

class requests_view(generic.ListView):
    template_name = "request/requests_page.html"
    context_object_name = 'all_requests'

    def get_queryset(self):
        return Request.objects.all()


class request_detail_view(generic.DetailView):
    model = Request
    template_name = "request/request_detail_page.html"

logos/templates/logos/base.html
<DOCTYPE! html>
{% load staticfiles %}
<html>

<head>
	<title>{% block title %} {% endblock %}</title>
	<meta charset="utf-8">
	<meta name="viewport" content = "width=device-width initial-scale=1">
	<link rel="shortcut-icon" href="file:///D:/bootstrap/icon.png" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Orbitron:700" rel="stylesheet"><script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="{% static 'logos/logos.css' %}">

</head>

<body>

	<nav class="navbar navbar-expand-md navbar-dark bg-primary shadow">
		
		<a class="navbar-brand border border-dark rounded " href="{% url 'logos:home_view' %}">
			<img class="ml-md-2" src="{% static 'logos/logo_icon.png' %}" width="40" height="40" >
			<strong class="mr-md-2" id="brand-LOGO"> LOGO</strong>
		</a>
		<button class="navbar-toggler border border-light" type="button" data-toggle="collapse" data-target="#navbar1" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
		<div class="collapse navbar-collapse" id="navbar1">
			<ul class = "navbar-nav" id="navbar-items">
				<li class="nav-item"><a class="nav-link" href="{% url 'logos:home_view' %}"><strong>HOME</strong></a></li>
				<li class="nav-item"><a class="nav-link" href="{% url 'logos:logos_view' %}"><strong>LOGOS</strong></a></li>
				<li class="nav-item"><a class="nav-link" href="#"><strong>REQUEST</strong></a></li>
				<li class="nav-item"><a class="nav-link" href="#"><strong>CREATE</strong></a></li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle " href="#" id="profiledropdown" data-toggle="dropdown"aria-haspopup="true" aria-expanded="false">
						<strong>PROFILE<strong>
					</a>
					<div class="dropdown-menu" aria-labelledby="profiledropdown">
						<a class="dropdown-item" href="#">1st Option</a>
						<a class="dropdown-item" href="#">2nd Option</a>
						<a class="dropdown-item" href="#">3rd Option</a>
						<a class="dropdown-item" href="#">4th Option</a>
					</div>
				</li>
			</ul>
		</div>
		<form class="form-inline mt-md-2 " action="{% url 'logos:search_view' %}" method="get" accept-charset="utf-8" >
			{% csrf_token %}
			<input class="form-control searchfield" type="text" placeholder="type to Search" name="q" aria-label="Search">
				<button class="btn btn-outline-success" type="submit"  id="search-icon"><img width="25px" height="25px"src="https://png.icons8.com/ios/100/000000/search.png">
				</button>
			</form>
	</nav>
	
	<div class="container-fluid">
	<p padding="3px"></p>
	</div>
	{% block content %}
	{% endblock %}

		
</body>
	<footer class="sticky-bottom" style=" padding-top:35px">
		<div class="container-fluid bg-dark" padding="3px" >
		<h1 >   website footers here
		</h1>
	</footer>
</html>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

logos/templates/logos/home_page.html
{% extends 'logos/index.html' %}

{% block title %} Home {% endblock %}

{% block content %}
	<div class="container " id="home-body">
	<h1><center><strong> About<strong></center></h1>
	<h4><p><center> This is your free LOGO design website.</center></p>
	<p><center>Feel free to request any kind of Logo as per your requirement </center></p>
	<p><center>or you can also contribute us by accepting the requests</center></p>
	<p><center>or you can make any random Logo independently. </center></p></h4>
	<p><center><h2>So go on Explore !!!</h2></center></p>

	<hr>
	</div>

{% endblock %}

logos/templates/logos/index.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<title>{% block title %} {% endblock %}</title>
	<meta charset="utf-8">
	<meta name="viewport" content = "width=device-width initial-scale=1">
	<link rel="icon" href="{% static 'logos/logo_icon.png' %}" type="image/x-icon" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Orbitron:700" rel="stylesheet"><script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="{% static 'logos/logo.css' %}">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

	
</head>

<body id="body-id" 	background="{% static 'logos/bg2.jpg' %}" >

	<nav class="navbar navbar-expand-md navbar-dark shadow " id="navigation_bar"  >
		<a class="navbar-brand border border-dark rounded " href="{% url 'logos:home_view' %}">
			<img class="ml-md-2" src="{% static 'logos/logo_icon.png' %}" width="40" height="40" >
			<strong class="mr-md-2" id="brand-LOGO"> LOGO</strong>
		</a>
		<button class="navbar-toggler border border-light sticky-right" style="position:relative"type="button" data-toggle="collapse" data-target="#navbar1" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
		<div class="collapse navbar-collapse " id="navbar1">
			<ul class = "navbar-nav " id="navbar-items">
				<li class="nav-item"><a class="nav-link" href="{% url 'logos:home_view' %}"><strong>HOME</strong></a></li>
				<li class="nav-item"><a class="nav-link" href="{% url 'logos:logos_view' %}"><strong>LOGOS</strong></a></li>
				<li class="nav-item"><a class="nav-link" href="{% url 'request:requests_view' %}"><strong>REQUEST/CREATE</strong></a></li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle " href="#" id="profiledropdown" data-toggle="dropdown"aria-haspopup="true" aria-expanded="false">
						<strong>PROFILE<strong>
					</a>
					<div class="dropdown-menu" aria-labelledby="profiledropdown">
						<a class="dropdown-item" href="#">1st Option</a>
						<a class="dropdown-item" href="#">2nd Option</a>
						<a class="dropdown-item" href="#">3rd Option</a>
						<a class="dropdown-item" href="#">4th Option</a>
					</div>
				</li>
			</ul>
		</div>
		<form class="form-inline mt-md-6 fixed-right " action="{% url 'logos:search_view' %}" method="get" accept-charset="utf-8" >
			{% csrf_token %}
			<input class="form-control searchfield" type="text" placeholder="type to Search" name="q" aria-label="Search">
				<button class="btn btn-outline-success" type="submit"  id="search-icon"><img width="25px" height="25px"src="https://png.icons8.com/ios/100/000000/search.png">
				</button>
		</form>
	</nav>
	
	<div class="container-fluid">
	<p padding="3px"></p>
	</div>
	{% block content %}
	{% endblock %}
	
	<footer >
		<h1 >   website footers here
		</h1>
	</footer>
	
</body>
	
</html>

logos/templates/logos/logo_detail_page.html
{% extends 'logos/index.html' %}

{% block title %} details {% endblock %}

{% block content %}

<div class=" row container-fluid" id="divison">
	<div class="col-md-6">
        Details for :<h1> {{ logo.logo_name }} </h1>
		<div>
            <img  class="img-fluid" alt="Responsive image"src="{{ logo.logo_img.url }}" width="400px"  >
		</div>

		<div>
			Type of Logo :  {{ logo.logo_type }}
		</div>

		<div>
			Created by : {{ logo.created_by }}
		</div>
		
	</div>
	
	<div class="col-md-6">
		<div class="row">
			<div class="col-md-6">
			<a href="{% url 'logos:logo_download_view' logo.pk %}"><button class="btn btn-block btn-outline-primary rounded">Download</button></a>
			</div>
			<div class="col-md-6">
			
			<button class="btn btn-block btn-outline-info rounded" data-toggle="modal" data-target="#{{ logo.pk }}-info">Info</button>
				<div class="modal fade " id="{{ logo.pk }}-info" >
					<div class=" modal-dialog "  >
						<div class="modal-content ">
							<div class="modal-header " style="height:5rem;background-color: #7502d3">
							<center><h1>{{ logo.logo_name }}</h1></center>
							<a href="" class="close"  data-dismiss="modal" aria-label="close">
								<span aria-hidden="true"><h1>&times;</h1></span>
							</a>
							</div>
							<div >
								<center><img  src="{{ logo.logo_img.url }}" width="200px"></center>
							</div>
							<div class="modal-body" id="info-body">
									<p>Logo Name : {{ logo.logo_name }}</p>
									<p>Type of Logo :  {{ logo.logo_type }}</p>
									<p>Software used : {{ logo.software_used }}</p>
									<p>Created by : {{ logo.created_by }}</p>
									<p>Requested by : {{ logo.requested_by }}</p>
									<p>Creation_date : {{ logo.create_date }}</p>
							</div>
							<div class="modal-footer container-fluid">
								<a href="{% url 'logos:logo_download_view' logo.pk %}" class="container-fluid">
									<button class="btn btn-block btn-outline-success">Download</button>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

logos/templates/logos/logos_page.html
{% extends 'logos/index.html' %}

{% block title %} Logos {% endblock %}

{% block content %}
<div class="container col-md-11" id="divison" >
	<div class="row" style="width:auto;" >
		{% for logos in all_logos %}
			<div class="col-md-3 col-sm-6 " style="padding:20px">
			<a href="{% url 'logos:logo_detail_view' logos.pk %}">
				<div class="  card border border-primary bg-dark" style="min-height:22rem;" >
					<div class="card-body"  >
						<div class="container" style="width:12rem";  >
							
							<img class="card img-top img-fluid " alt="Responsive image" src="{{ logos.logo_img.url }}" >
							
						</div>
			</a>
						<div class="card-title"><h2>{{ logos.logo_name }}</h2>
						</div>
						<div class="card-subtitle text-muted">
								<h4>{{ logos.logo_type }}</h4>
						</div>
						
							<div class="row container-fluid">
								<div class="col-md-4 " >
									<a href="{% url 'logos:logo_detail_view' logos.pk %}"><button class="btn btn-outline-info">View</button></a>
								</div>
								<div class="col-md-4" >
									<a href="{% url 'logos:logo_download_view' logos.pk %}"><button class="btn btn-outline-success">Save</button></a>
								</div>
								<div class="col-md-4 " >
									<button class="btn  btn-outline-secondary " data-toggle="modal" data-target="#{{ logos.pk }}-info">Info</button>
										<div class="modal fade" id="{{ logos.pk }}-info" >
											<div class=" modal-dialog"  >
												<div class="modal-content ">
													<div class="modal-header " style="height:5rem;background-color: #7502d3">
													<center><h1>{{ logos.logo_name }}</h1></center>
													<a href="" class="close"  data-dismiss="modal" aria-label="close">
														<span aria-hidden="true"><h1>&times;</h1></span>
													</a>
													</div>
													<div >
														<center><img  src="{{ logos.logo_img.url }}" width="200px"></center>
													</div>
													<div class="modal-body" id="info-body">
															<p>Logo Name : {{ logos.logo_name }}</p>
															<p>Type of Logo :  {{ logos.logo_type }}</p>
															<p>Software used : {{ logos.software_used }}</p>
															<p>Created by : {{ logos.created_by }}</p>
															<p>Requested by : {{ logos.requested_by }}</p>
															<p>Creation_date : {{ logos.create_date }}</p>
													</div>
													<div class="modal-footer container-fluid">
														<a href="{% url 'logos:logo_download_view' logos.pk %}" class="container-fluid">
															<button class="btn btn-block btn-outline-success">Download</button>
														</a>
													</div>
												</div>
											</div>
										</div>
								</div>
							</div>		
					</div>
				</div>
		</div>
		{% endfor %}
	</div>
</div>

{% endblock %}

logos/templates/logos/search_page.html
{% extends 'logos/index.html' %}

{% block title %} search-result {% endblock %}

{% block content %}
	<div class="container">
	<h1><center><strong> Searchresult for : {{ query }}<strong></center></h1>
	<hr>
	</div>

	<div class="container" id="divison">
	<div class="row">
	{% if searched_logos %}
	{% for logos in searched_logos %}
		
		<div class="col-md-3 col-sm-6 ">	
			<a href="{% url 'logos:logo_detail_view' logos.pk %}">
				<div class="card border border-primary bg-light" style="height:22rem;" >
					<div class="card-body"  >
						<div class="container  " style="width:12rem; ">
							
							<img class="card-img-top " image" src="{{ logos.logo_img.url }}" >
							
						</div>
			</a>
						<div class="card-title"><h2>{{ logos.logo_name }}</h2></div>
							<div class="card-subtitle text-muted">
								<h4>{{ logos.logo_type }}</h4>
							</div>
						
							<div class="row container">
								<div class="col-md-4" >
									<a href="{% url 'logos:logo_detail_view' logos.pk %}"><button class="btn btn-outline-info">View</button></a>
								</div>
								<div class="col-md-4" >
									<a href="{% url 'logos:logo_download_view' logos.pk %}"><button class="btn btn-outline-success">Save</button></a>
								</div>
								<div class="col-md-4 " >
										
										<button class="btn  btn-outline-secondary " data-toggle="modal" data-target="#{{ logos.pk }}-info">Info</button>
											<div class="modal fade " id="{{ logos.pk }}-info" >
												<div class=" modal-dialog "  >
													<div class="modal-content ">
														<div class="modal-header " style="height:5rem;background-color: #7502d3">
														<center><h1>{{ logos.logo_name }}</h1></center>
														<a href="" class="close"  data-dismiss="modal" aria-label="close">
															<span aria-hidden="true"><h1>&times;</h1></span>
														</a>
														</div>
														<div >
															<center><img  src="{{ logos.logo_img.url }}" width="200px"></center>
														</div>
														<div class="modal-body" id="info-body">
																<p>Logo Name : {{ logos.logo_name }}</p>
																<p>Type of Logo :  {{ logos.logo_type }}</p>
																<p>Software used : {{ logos.software_used }}</p>
																<p>Created by : {{ logos.created_by }}</p>
																<p>Requested by : {{ logos.requested_by }}</p>
																<p>Creation_date : {{ logos.create_date }}</p>
														</div>
														<div class="modal-footer container-fluid">
															<a href="{% url 'logos:logo_download_view' logos.pk %}" class="container-fluid">
																<button class="btn btn-block btn-outline-success">Download</button>
															</a>
														</div>
													</div>
												</div>
											</div>
									
								</div>
							</div>		
					</div>
				</div>
		</div>
		{% endfor %}
		
		{% else %}
			<div class = "container">
				<h2>No item match your search</h2>
				<p> <h4>try typing different text </h4></p>
				<p><h2>HINTS : </h2></p>
				<p><ul>
						<li> search by icon name </li>
						<li> search by icon type</li>
						<li> search by artist name </li>
				</ul></p>
			</div>
			
		{% endif %}
		
		
	</div>
</div>

{% endblock %}

request/templates/request/info-modal.html
{% extends 'request/requests_page.html' %}

{% block info-modal%}
	<button class="btn btn-block btn-outline-secondary rounded" data-toggle="modal" data-target="#info-modal">Info</button>
	<div class="modal fade " id="info-modal" >
		<div class=" modal-dialog "  >
			<div class="modal-content ">
				<div class="modal-header " style="height:5rem;background-color: #7502d3">
				<center><h1>{{ request.requested_by }}</h1></center>
				<a href="" class="close"  data-dismiss="modal" aria-label="close">
					<span aria-hidden="true"><h1>&times;</h1></span>
				</a>
				</div>
				
				<div class="modal-body" style="padding-left:10px;">
						<p>Requested By : {{ request.requested_by }}</p>
						<p>Type of Logo :  {{ request.logo_type }}</p>
						<p>Email : {{ request.email }}</p>
						<p>Usage : {{ request.usage }}</p>
						<p>Discription : {{ request.discription }}</p>
						<p>Request date : {{ request.request_date }}</p>
				</div>
				<div class="modal-footer container-fluid">
					<a href="#" class="container-fluid">
						<button class="btn btn-block btn-outline-success">Create</button>
					</a>
				</div>
			</div>
		</div>
	</div>
	
{% endblock %}

request/templates/request/request_detail_page.html
{% extends 'logos/index.html' %}

{% block title %} details {% endblock %}

{% block content %}
<div class ="container" id="divison">
	<div >
        Details for :<h1> {{ request.requested_by }} </h1>
	</div>
	<div>
		<p> Type of Logo :  {{ request.logo_type }}</p>
	</div>
	<div>
		<p> Email : {{ request.email }}</p>
	</div>
		

	
	<div class="col-md-6">
		<div class="row">
			<div class="col-md-6">
			<a href="#"><button class="btn btn-block btn-outline-primary rounded">Create</button></a>
			</div>
			<div class="col-md-6">
			
			<button class="btn btn-block btn-outline-info rounded" data-toggle="modal" data-target="#{{ request.pk }}-info">Info</button>
				<div class="modal fade " id="{{ request.pk }}-info" >
					<div class=" modal-dialog "  >
						<div class="modal-content ">
							<div class="modal-header " style="height:5rem;background-color: #7502d3">
							<center><h1>{{ request.requested_by }}</h1></center>
							<a href="" class="close"  data-dismiss="modal" aria-label="close">
								<span aria-hidden="true"><h1>&times;</h1></span>
							</a>
							</div>
							
							<div class="modal-body" id="info-body">
									<p>Requested By : {{ request.requested_by }}</p>
									<p>Type of Logo :  {{ request.logo_type }}</p>
									<p>Email : {{ request.email }}</p>
									<p>Usage : {{ request.usage }}</p>
									<p>Discription : {{ request.discription }}</p>
									<p>Request date : {{ request.request_date }}</p>
							</div>
							<div class="modal-footer container-fluid">
								<a href="#" class="container-fluid">
									<button class="btn btn-block btn-outline-success">Create</button>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

request/templates/request/requests_page.html
{% extends 'logos/index.html' %}

{% block title %} Requests {% endblock %}

{% block content %}
<div class="container" id="divison" >
	<div class="row">
		{% for request in all_requests %}
		<div class="col-md-6 col-sm-6 ">	
			<a href="{% url 'request:request_detail_view' request.pk %}">
				<div class="card border border-primary bg-dark" style="height:15rem;" >
					<div class="card-body"  >
						
			</a>
						<div class="card-title"><h2>{{ request.logo_type }}</h2>
						</div>
						<div class="card-subtitle text-muted">
								<h4>{{ request.requested_by }}</h4>
						</div>
						<div class="container" >
						<p style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ request.discription}}</p>
						</div>
							<div class="row container-fluid">
								<div class="col-md-6 " >
									<a href="{% url 'request:request_detail_view' request.pk %}"><button class="btn btn-block btn-outline-info">View</button></a>
								</div>
								
								<div class="col-md-6 " >
										
										<button class="btn  btn-outline-secondary btn-block " data-toggle="modal" data-target="#{{ request.pk }}-info">Info</button>
											<div class="modal fade " id="{{ request.pk }}-info" >
												<div class=" modal-dialog "  >
													<div class="modal-content ">
														<div class="modal-header " style="height:5rem;background-color: #7502d3">
														<center><h1>{{ request.requested_by }}</h1></center>
														<a href="" class="close"  data-dismiss="modal" aria-label="close">
															<span aria-hidden="true"><h1>&times;</h1></span>
														</a>
														</div>
														
														<div class="modal-body" id="info-body">
																<p>Requested By : {{ request.requested_by }}</p>
																<p>Type of Logo :  {{ request.logo_type }}</p>
																<p>Email : {{ request.email }}</p>
																<p>Usage : {{ request.usage }}</p>
																<p>Discription : {{ request.discription }}</p>
																<p>Request date : {{ request.request_date }}</p>
														</div>
														<div class="modal-footer container-fluid">
															<a href="#" class="container-fluid">
																<button class="btn btn-block btn-outline-success">Create</button>
															</a>
														</div>
													</div>
												</div>
											</div>
									
								</div>
							</div>		
					</div>
				</div>
		</div>
		{% endfor %}
	</div>
</div>

{% endblock %}